services:
  db:
    image: postgres
    container_name: medsched-postgres
    restart: always
    volumes:
      - ../scripts:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:?Defina DB_PASSWORD no arquivo .env}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_DB: ${DB_NAME:-MedSched}
    ports:
      - "5433:5432"
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: medsched-webapi
    ports:
      - "4000:8080" 
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      DOTNET_ENVIRONMENT: "Staging"
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:?Defina DB_PASSWORD no arquivo .env}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ""
      Jwt__Audience: ${JWT_AUDIENCE:-med-sched.users}
      Jwt__ExpiresInMinutes: 15
      Jwt__Issuer: ${JWT_ISSUER:-med-sched.webapi}
      Jwt__SecretKey: ${JWT_SECRET_KEY:?Defina JWT_SECRET_KEY no arquivo .env}
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    depends_on:
     - db
